apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: app-sringboot
      version: blue
  template:
    metadata:
      labels:
        app: app-sringboot
        version: blue
    spec:
      containers:
        - name: app-sringboot
          image: blue-image
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3