apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-deployment
spec:
  strategy:
    type: Recreate
#    type: RollingUpdate
#    rollingUpdate:
#      maxUnavailable: 0
#      maxSurge: 1
  replicas: 5
  selector:
    matchLabels:
      app: app-sringboot
  template:
    metadata:
      labels:
        app: app-sringboot
    spec:
      containers:
        - name: app-sringboot
          image: lab-image
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3