apiVersion: v1
kind: Service
metadata:
  name: lab-service
spec:
  type: NodePort
  selector:
    app: app-sringboot
#    version: blue
#    version: green
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30007